import Sidebar from "@/components/sideBar/Sidebar";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "employee manage system",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="grid grid-cols-12 gap-4">
          <aside className="col-span-2 min-h-screen bg-e-primary">
            <Sidebar />
          </aside>
          <article className="col-span-10">{children}</article>
        </main>
      </body>
    </html>
  );
}
